import Navbar from './components/Navbar'
import './globals.css'
import { Montserrat } from 'next/font/google'


const bodyfonts = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Crud Next',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bodyfonts.className}>
      <Navbar />
      {children}</body>
    </html>
  )
}
